# Generated by Django 3.1.7 on 2021-04-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='image',
            field=models.FileField(null=True, upload_to='subprofile/', verbose_name=''),
        ),
    ]
